"""Ajoute candidate_profiles

Revision ID: 039412531390
Revises: 47b6a179d2de
Create Date: 2026-09-12 15:59:40.666150
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "039412531390"
down_revision: str | None = "47b6a179d2de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_profiles",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("availability", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "total_experience", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("experiences", sa.JSON(), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("formations", sa.JSON(), nullable=True),
        sa.Column("languages", sa.JSON(), nullable=True),
        sa.Column("certifications", sa.JSON(), nullable=True),
        sa.Column("contract_types", sa.JSON(), nullable=True),
        sa.Column("remote_preferences", sa.JSON(), nullable=True),
        sa.Column("mobility", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("salary_target", sa.Integer(), nullable=True),
        sa.Column("raw_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_profiles_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_candidate_profiles_user_id"), ["user_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_profiles_user_id"))
        batch_op.drop_index(batch_op.f("ix_candidate_profiles_id"))

    op.drop_table("candidate_profiles")
    # ### end Alembic commands ###
