"""add leads and email queue

Revision ID: 47b6a179d2de
Revises: d55d7f12fae8
Create Date: 2026-07-20 15:29:43.068421
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47b6a179d2de"
down_revision: str | None = "d55d7f12fae8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_messages",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("to_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_html", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_email_messages_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_email_messages_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_email_messages_to_email"), ["to_email"], unique=False
        )

    op.create_table(
        "leads",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_leads_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_leads_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leads_id"))
        batch_op.drop_index(batch_op.f("ix_leads_email"))

    op.drop_table("leads")
    with op.batch_alter_table("email_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_messages_to_email"))
        batch_op.drop_index(batch_op.f("ix_email_messages_status"))
        batch_op.drop_index(batch_op.f("ix_email_messages_id"))

    op.drop_table("email_messages")
    # ### end Alembic commands ###
